# Generated by Django 5.2.7 on 2025-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
