# Generated by Django 5.2.7 on 2025-12-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_alamat_mahasiswa_no_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jurusan',
            field=models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Sistem Informasi', 'Sistem Informasi'), ('Teknik Komputer', 'Teknik Komputer'), ('Manajemen Informatika', 'Manajemen Informatika')], default='Teknik Informatika', max_length=50),
        ),
    ]
